name: Python Unittest ChurchToolsAPI

on: [ push, pull_request ]

env:
  CT_TOKEN: ${{ secrets.CT_TOKEN }}
  CT_USERS: ${{ secrets.CT_USERS }}
  CT_DOMAIN: ${{ vars.CT_DOMAIN }}

jobs:
  list-domain:
    runs-on: ubuntu-latest
    environment: ev_kirche_baiersbronn
    steps:
      - name: show CT_DOMAIN for this job
        run: echo $CT_DOMAIN
  test:
    runs-on: ubuntu-latest
    environment: ev_kirche_baiersbronn
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.x'
      
      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false  # Skip creating a virtual environment
        env:
          POETRY_HOME: ${{ github.workspace }}/.poetry

      - name: Install project dependencies
        run: |
          poetry install
        env:
          POETRY_HOME: ${{ github.workspace }}/.poetry

      - name: Run unittests
        run: |
          python -m unittest tests.test_churchtools_api
        env:
            POETRY_HOME: ${{ github.workspace }}/.poetry
          