name: Create Release
on:
  push:
    tags:
      - 'v*'
  pull_request:
    tags:
      - 'v*'
jobs:
  build:
    if: github.ref == 'refs/heads/master' OR github.ref == 'refs/heads/dev_benste'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Version from Python
        run: echo "VERSION=$(python3 -c 'import versions; print(versions.VERSION)')" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Run setup.py
        run: python setup.py sdist bdist_wheel

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          name: Version ${{env.VERSION}}
          body: |
            Automated Release preparation using Git Tag
            - make sure tests didn't fail
            - upload package files
            - needs to be published from draft online
          draft: true
          prerelease: false
          artifacts: dist/*
