name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: googleapis/release-please-action 
        with:
          release-type: python