name: Build & Release Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.x

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false  # Skip creating a virtual environment
        env:
          POETRY_HOME: ${{ github.workspace }}/.poetry

      - name: Install project dependencies
        run: poetry install
        env:
          POETRY_HOME: ${{ github.workspace }}/.poetry

      - name: Build package
        run: poetry build
        env:
          POETRY_HOME: ${{ github.workspace }}/.poetry

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ env.VERSION }}
          name: Version ${{ env.VERSION }}
          body: |
            Automated Release preparation using Git Tag
            - make sure tests didn't fail
            - needs to be published from draft online
            
            Install as package using:
            pip install git+https://github.com/bensteUEM/ChurchToolsAPI.git@${{env.VERSION}}#egg=churchtools-api
            
          draft: true
          prerelease: false
          artifacts: dist/*
